# Generated by Django 4.1.3 on 2022-12-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepoint',
            old_name='puissance_max_w',
            new_name='max_power_w',
        ),
    ]
