# Generated by Django 4.1.3 on 2022-12-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoints', '0002_rename_puissance_max_w_chargepoint_max_power_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='chargepoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargepoints.chargepoint'),
        ),
    ]
